### ISSUE TITLE
No module named secrets

### ISSUE THREAD

**Issue by maxcado** [Destiner/blocksmith#5]
Hello, this code looks interesting and potentially useful, however upon installing in python 2.7 on linux -- Ubuntu 18.1 there's the error No module names secrets. There an issue in line 1 of _init_.py  - from.generator import KeyGenerator and line 3 of generator.py for import secrets.

Note that there were no errors during installation. It's just the above issues after trying to 'import blocksmith'.

**Comment by JRafiei** [comment]
Hi @maxcado. There is no secrets module in python 2.7. You should use this package on an environment with python 3.6 or above installed.

**Comment by maxcado** [comment]
Good day @JRafiei. I've installed using python 3.6 and get the following errors:
>>>import blocksmith
Traceback (most recent call last):
  File "<stdin>", line 1, n <module>
 File "/usr/local/lib/python3.6/dist-packages/blocksmith/_init_.py", line 3,  in <module> from.ethereum import EthereumWallet
File "usr/local/lib/python3.6/dist-packages/blocksmith/ethereum.py", line 3, in <module> from Crypto.Hash import keccak
File "/home/maxcado/.local/lib/python3.6/site-packages/Crypto/Hash/keccak.py", line 33, in <module> from Crypto.Util._raw_api import (load_pycrptodome_raw_lib, 
File "/home/maxcado/.local/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 34, in <module> from Crypto.Util.py3compat import byte_sring
Import Error: cannot import name 'byte _string'
>>>

**Comment by falcon141** [comment]
root@localhost:/sdcard/blocksmith/blocksmith# sudo pip install secrets
